### PR TITLE
Pin composer version

### PR DESCRIPTION
**Pull request by gordcorp**
I've been bitten too many times by having dependencies self-update themselves - it's better if we version control things like this.

### CODE REVIEW

**Comment by gordcorp** [comment]
Hmm I pinned us to the latest available version of composer, however I just notice `"composer/composer": "^1.5",` is in the composer.json - having multiple versions might also give us issues... @imperator99 does composer even need to be in composer.json? I was expecting to just have composer installed globally.

**Comment by imperator99** [comment]
@gordcorp not really sure. Composer is usually installed globally on a local machine but in a transient environment like a docker or CF container that wouldn't be the case. Clearly composer has to be installed for the composer.json to even run so by definition it is already installed. I can't see anything about it online so I am assuming that it isn't required in composer.json. If it is a dependency from some other package then it'll get installed that way anyway.

**Comment by gordcorp** [comment]
Ok cheers I'll remove composer out of composer.json, and see if that works for us.

**Comment by gordcorp** [comment]
It seems to work just fine for me in circle and locally

**Pull request merged**
